name: Waka Readme Worfklow

on:
  schedule:
    # Runs at 4:20 (https://crontab.guru for help)
    - cron: '20 4 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Profile Readme Development Stats
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@V3
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: False
          SHOW_LINES_OF_CODE: True
          SHOW_UPDATED_DATE: True
