name: Waka Readme Worfklow

on:
  schedule:
    # Runs at 12:30 (https://crontab.guru for help)
    - cron: '30 12 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LOC_CHART: False
          SHOW_LINES_OF_CODE: True
          SHOW_UPDATED_DATE: True
